server:
  port: 8010

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dlog?serverTimezone=GMT%2B8
      username: root
      password: 123456
#  redis:
#    port: 6379

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.moon.dlog.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
